Bakery/authetication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from .forms import RegistrationForm, LoginForm  # Assuming forms.py contains the form definitions
from Bakery.database import Users
from Bakery.factory import db,bcrypt
from flask_login import login_required, login_user, logout_user, current_user

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/',methods=['GET','POST'])
def index():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data) and user.is_active:
             login_user(user,remember=form.remember.data)
             #next = request.args.get('next')

             if user.id == 1 or user.id == 2:
                 session['user_id'] = user.id
                 flash("Login Successfully",'info')
                 return redirect(url_for('users.boss'))
             elif user.position_as == 'Manunuzi':
                 session['position_as'] = "Manunuzi"
                 session['user'] = user.id
                 flash("Login Successfully",'info')
                 return redirect(url_for('users.manunuzi'))
             elif user.position_as == 'Mpishi':
                 session['position_as'] = "Mpishi"
                 session['user_id'] = user.id
                 flash("Login Successfully",'info')
                 return redirect(url_for('users.mpishi'))
             elif user.position_as == 'Mauzo':
                 session['position_as'] = "Mauzo"
                 session['user_id'] = user.id
                 flash("Login Successfully",'info') 
                 return redirect(url_for('users.mauzo'))
             elif user.position_as == 'Store':
                 session['position_as'] = "Store"
                 session['user_id'] = user.id
                 flash("Login Successfully",'info') 
                 return redirect(url_for('users.store'))
             else:
                 flash("You are not allowed to access this page",'warning')
                 return redirect(url_for('auth.index'))
        else:
            flash("Login Unsuccessfully check Email and Password Or Maybe Deactivated",'warning')
    return render_template('login.html', title="login",form=form)
    

@auth_bp.route('/registerUser',methods=['GET','POST'])
def registerUser():
    form = RegistrationForm()
    if form.validate_on_submit():
        hash_passwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users(name=form.username.data,email=form.email.data,is_active=True,position_as=form.position.data,phone_no=form.phone.data,password=hash_passwd)
        db.session.add(user)
        db.session.commit()
        flash("User is successfully registered",'primary')
        return redirect(url_for('users.user_status'))
    return render_template('registration.html', form=form)

@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logout Successfully",'info')
    return redirect(url_for('auth.index'))


            

Bakery/users/routes.py
from flask import Blueprint, render_template, request,url_for,flash,redirect,session, make_response
from .forms import (ManunuziForm,BidhaaForm,MauzoForm,Mabadiliko_BeiForm,LipaForm,MapatoForm,MatumiziForm,
                    UzalishajiForm,MadeniForm,MpishiForm,StoreForm)
from Bakery.database import ManunuziData,Bidhaa,Uzalishaji,Mauzo,Madeni,Mpishi,Store,Mapato,Matumizi,Users
from Bakery.factory import db
from flask_login import current_user, login_required
from datetime import datetime, date, timedelta
from Bakery.authorization.validate import manunuzi_required, mauzo_required, mpishi_required, admin_required, store_required

users = Blueprint('users', __name__)

@users.route('/manunuzi',methods=['GET','POST'])
@login_required
@manunuzi_required
def manunuzi():
    form = ManunuziForm()
    
    if form.validate_on_submit():
        mf = form.maligafi.data
        un = form.unit.data
        idadi = form.idadi.data
        jumla = idadi * form.bei.data
        manunuziData = ManunuziData(maligafi=mf,unit=un,idadi=idadi,bei=jumla,user_id=session['user_id'])
        matumizi = Matumizi(kiasi=jumla,aina="Manunuzi")
        db.session.add(matumizi)
        db.session.add(manunuziData)
        db.session.commit()
        
        return redirect(url_for('users.manunuzi'))
    else:

        manunuzidisp = ManunuziData.query.all()
        return render_template('manunuzi.html',manunuzidisp=manunuzidisp,form=form)
    
    


@users.route('/mauzo',methods=['GET','POST'])
@login_required
@mauzo_required
def mauzo():
    form = MauzoForm()
    
    if form.validate_on_submit():
        #mz means mauzo variable
        #create bei and foreign key from bidhaa
        bid_data = Bidhaa.query.filter_by(b_name=form.bid.data).first()
        mzs = Mauzo.query.filter_by(bid_id=bid_data.id).first()
        if mzs:
          baki = mzs.jumla - form.b_uza.data
          if baki >= 0:      
                bei = bid_data.b_bei * form.b_uza.data
                mzs.b_uza = form.b_uza.data
                mzs.b_bei_uza = bei 
                mzs.jumla = baki
                mapato = Mapato(kiasi=bei,aina="Mauzo")
                db.session.add(mapato)
                db.session.commit()
                return redirect(url_for('users.mauzo'))
          else:
                return f"Idadi iliyotoka {form.b_uza.data} ni kubwa kuliko kiasi kilichopo, Angalia kwa makini au wasiliana na Wahusika wa Uzalishaji"
        else:
            return f"Bidhaa hiyo bado haijaingia wasiliana na Wahusika wa Uzalishaji"
    else:
        #mzdisp for mauzo Query data
        mzdisp = Mauzo.query.order_by(Mauzo.id.desc()).all()
        return render_template('mauzo.html',form=form,title="Mauzo",mzdisp=mzdisp)

@users.route('/uzalishaji',methods=['GET','POST'])
@login_required
@mauzo_required
def uzalishaji():
    form = UzalishajiForm()
    if form.validate_on_submit():
        #uzal for uzalishaji variable and bid_data explained in mauzo route
        bid_data = Bidhaa.query.filter_by(b_name=form.bid.data).first()
        
        uzal = Uzalishaji(b_jumla = form.jumla.data, bid_id = bid_data.id)
        db.session.add(uzal)
        #db.session.commit()
        #update mauzo table with the new data
        mz = Mauzo.query.filter_by(bid_id=bid_data.id).first()
        if mz:
            mz.jumla = mz.jumla + form.jumla.data
            
        else:
            mauzo = Mauzo(jumla=form.jumla.data,bid_id=bid_data.id,user_id=session['user_id'])
            db.session.add(mauzo)
        db.session.commit()
        #flash message
        flash('Data is Sent Successfully','primary')
        return redirect(url_for('users.uzalishaji'))
    else:
        #uzaldisp for displaying in uzalishaji.html
        uzaldisp = Uzalishaji.query.all()
        return render_template('uzalishaji.html',form=form,uzaldisp=uzaldisp)
        
@users.route('/bidhaa',methods=['POST','GET'])
@login_required
@mauzo_required
def bidhaa():

    form = BidhaaForm()
    if form.validate_on_submit():
        bid = Bidhaa(b_name=form.bidhaa.data,b_bei=form.bei.data)
        db.session.add(bid)
        db.session.commit()
        flash('New Entry Added','info')
        return redirect(url_for('users.bidhaa'))
    else:
        bid = Bidhaa.query.all()
        return render_template('bidhaa.html', form=form,bid=bid)
    
@users.route('/madeni',methods=['GET','POST'])
@login_required
@mauzo_required
def madeni():
    form = MadeniForm()
    collapse = False
    if form.validate_on_submit():
        # Get the selected product from the dropdown
        bid_data = Bidhaa.query.filter_by(b_name=form.bidhaa.data).first()
        baki = (bid_data.b_bei * form.idadi.data) - form.kiasi_kalipa.data

        #update number of product in Mauzo Table
        mz = Mauzo.query.filter_by(bid_id=bid_data.id).first()
        if mz:
            baki = mz.jumla - form.idadi.data
            if baki >= 0: 
                k_baki = (bid_data.b_bei * form.idadi.data) - form.kiasi_kalipa.data
                mz.jumla = baki
                md = Madeni(name=form.name.data, phone=form.phone.data, kiasi_kalipa=form.kiasi_kalipa.data, kiasi_baki=k_baki,status=form.idadi.data, bid_id=bid_data.id)
                mapato = Mapato(kiasi=form.kiasi_kalipa.data,aina="From Madeni")
                db.session.add(mapato)
                db.session.add(md)
                db.session.commit()
                collapse = False
                flash('New Entry Added','info')
                return redirect(url_for('users.madeni'))
            else:
                return f"Idadi iliyotoka {form.idadi.data} ni kubwa kuliko kiasi kilichopo, Angalia kwa makini au wasiliana na Wahusika wa Uzalishaji"
        else:
            return f"Bidhaa hiyo bado haijaingia wasiliana na Wahusika wa Uzalishaji"
    else:
        collapse = False
        md = Madeni.query.order_by(Madeni.id.desc()).all()
        return render_template('madeni.html', form=form, md=md, collapse=collapse)


@users.route('/mpishi',methods=['GET','POST'])
@login_required
@mpishi_required
def mpishi():
    form = MpishiForm()
    if form.validate_on_submit():
        #loading bidhaa data
        bid_data = Bidhaa.query.filter_by(b_name=form.bid.data).first()
        
        #inserting data to the database
        mpishi = Mpishi(pondo=form.pondo.data, idadi=form.idadi.data,bid_id=bid_data.id,user_id=session['user_id'])
        db.session.add(mpishi)
        db.session.commit()

        return redirect(url_for('users.mpishi'))
    else:

        #display on the screen 
        mpdsp = Mpishi.query.all()
        return render_template('mpishi.html', form=form, mpdsp=mpdsp)


@users.route('/store',methods=['GET','POST'])
@login_required
@store_required
def store():
    form = StoreForm()
    if form.validate_on_submit():

        #inserting data to the database
        store = Store(maligafi=form.maligafi.data, units=form.unit.data,idadi=form.idadi.data,user_id=session['user_id'])
        db.session.add(store)
        db.session.commit()
        return redirect(url_for('users.store'))
    else:
        
        #display on the screen 
        strdsp = Store.query.all()
        response = make_response(render_template('store.html', form=form, strdsp=strdsp))
        # prevent browser from caching
        response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Expires'] = '0'
        return response

@users.route('/B_bei/<int:id>',methods=['GET','POST'])
@login_required
def mabaliko_Bei(id):
    bid_data = Bidhaa.query.get_or_404(id)
    form = Mabadiliko_BeiForm()
    if form.validate_on_submit():
        bid_data.b_bei = form.bei.data
        db.session.commit()
        flash('Bei updated','info')
        return redirect(url_for('users.bidhaa'))
    else:
        return render_template('bei.html',form=form)
        

@users.route('/lipa/<int:id>',methods=['GET','POST'])
@login_required
def lipa(id):
    deni = Madeni.query.get_or_404(id)
    form = LipaForm()
    if form.validate_on_submit():
        deni.kiasi_kalipa = form.lipa.data + deni.kiasi_kalipa
        deni.kiasi_baki = (deni.bid.b_bei * deni.status) - deni.kiasi_kalipa
        mapato = Mapato(kiasi=form.lipa.data,aina="Lipa Deni")
        db.session.add(mapato)
        db.session.commit()
        flash('Deni updated','info')
        return redirect(url_for('users.madeni'))
    else:
        return render_template('lipa.html',form=form)
    
# These are boss (Admin) routes all

@users.route('/boss',methods=['GET','POST'])
@login_required
@admin_required
def boss():

    #get Mapato and Matumizi data all 
    mapato = Mapato.query.order_by(Mapato.date.desc()).all()
    matumizi = Matumizi.query.order_by(Matumizi.date.desc()).all()

    # Get 7 days before today + today
    today = date.today()
    
    date_range = [(today - timedelta(days=i)) for i in range(7)]
    date_range.remove(today)

    return render_template('boss.html',mapato=mapato,matumizi=matumizi,date_range=date_range,tarehe=today)
    
@users.route('/b_bidhaa', methods=['GET', 'POST'])
@login_required
@admin_required
def b_bidhaa():
    bid = Bidhaa.query.all()
    return render_template('b_bidhaa.html',bid=bid)

@users.route('/b_store', methods=['GET', 'POST'])
@login_required
@admin_required
def b_store():
    strdsp = Store.query.all()
    return render_template('b_store.html',strdsp=strdsp)

@users.route('/b_manunuzi', methods=['GET', 'POST'])
@login_required
@admin_required
def b_manunuzi():
    manunuzidisp = ManunuziData.query.all()
    return render_template('b_manunuzi.html',manunuzidisp=manunuzidisp)

@users.route('/deactivate_account/<int:id>', methods=['GET', 'POST'])
@login_required
def deactivate_account(id):
    #current_user.is_active = False
    user = Users.query.get_or_404(id)
    user.is_active = False
    db.session.commit()
    return redirect(url_for('users.user_status'))

Bakery/templates/b_mauzo.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome boss (Dashboard)</title>

    <!-- Custom     CSS for this page-->
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/mystyle.css')}}">
    <style>
        .dropdown-toggle::after {
            display: none !important;
        }
    </style>

</head>

<body>


    <!-- Page Wrapper -->

    <!-- Content Wrapper -->
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Admin Page </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.boss')}}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading d-flex justify-content-center">
            <span class="">Taarifa</span>
        </div>

        <!-- Nav Item - Components Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_bidhaa')}}" aria-expanded="false" aria-controls="collapseTwo">

                <span>Bidhaa</span>
            </a>

        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_manunuzi')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Manunuzi</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_uzalishaji')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Uzalishaji</span>
            </a>

        </li>
        <li class="nav-item active">
            <a class="nav-link " href="{{url_for('users.b_mauzo')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Mauzo</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_madeni')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Madeni</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_store')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Store</span>
            </a>

        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading d-flex justify-content-center">
            <span class="">User Management</span>
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.user_status')}}" aria-expanded="false"
                aria-controls="collapsePages">

                <span>User Status</span>
            </a>

        </li>







    </ul>
    <!-- End of Sidebar -->

    <div class="content-wrapper">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <ul class="navbar-nav ms-auto pr-2">
                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{current_user.name}}</span>
                        <img class="img-profile rounded-circle"
                            src="{{url_for('static',filename='img/undraw_profile.svg')}}">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                        aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{url_for('auth.index')}}" data-toggle="modal"
                            data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <div class="pt-3">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

        <div class="container-fluid mt-4">
            <h1>Welcome {{current_user.name}}!</h1>


            <!-- Matumizi -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 text-center">
                    <h3 class="m-0 font-weight-bold ">Mauzo Ya Kila Siku</h3>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <th>Tarehe</th>
                            <th>Bidhaa</th>
                            <th>Bei</th>
                            <th>Bidhaa Zilizotoka</th>
                            <th>Bidhaa Zilizopo</th>
                            <th>Tsh</th>
                            <th>Jina</th>

                        </tr>
                        {% if mzdisp %}
                        {% for mz in mzdisp %}
                        <tr>

                            <td>{{ mz.date }}</td>
                            <td>{{ mz.bid.b_name }}</td>
                            <td>{{ mz.bid.b_bei }}</td>
                            <td>{{ mz.b_uza}}</td>
                            <td>{{mz.jumla}}</td>
                            <td>{{ mz.b_bei_uza }}</td>
                            <td>{{mz.seller.name}}</td>

                        </tr>
                        {% endfor %}
                        {% endif %}

                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>

</html>

Bakery/templates/user_status.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome boss (Dashboard)</title>

    <!-- Custom     CSS for this page-->
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/mystyle.css')}}">
    <style>
        .dropdown-toggle::after {
            display: none !important;
        }
    </style>

</head>

<body>


    <!-- Page Wrapper -->

    <!-- Content Wrapper -->
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Admin Page </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.boss')}}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading d-flex justify-content-center">
            <span class="">Taarifa</span>
        </div>

        <!-- Nav Item - Components Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_bidhaa')}}" aria-expanded="false" aria-controls="collapseTwo">

                <span>Bidhaa</span>
            </a>

        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_manunuzi')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Manunuzi</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_uzalishaji')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Uzalishaji</span>
            </a>

        </li>
        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_mauzo')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Mauzo</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_madeni')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Madeni</span>
            </a>

        </li>

        <li class="nav-item">
            <a class="nav-link " href="{{url_for('users.b_store')}}" aria-expanded="false"
                aria-controls="collapseUtilities">

                <span>Store</span>
            </a>

        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading d-flex justify-content-center">
            <span class="">User Management</span>
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item active">
            <a class="nav-link " href="{{url_for('users.user_status')}}" aria-expanded="false"
                aria-controls="collapsePages">

                <span>User Status</span>
            </a>

        </li>







    </ul>
    <!-- End of Sidebar -->

    <div class="content-wrapper">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <ul class="navbar-nav ms-auto pr-2">
                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{current_user.name}}</span>
                        <img class="img-profile rounded-circle"
                            src="{{url_for('static',filename='img/undraw_profile.svg')}}">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                        aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{url_for('auth.index')}}" data-toggle="modal"
                            data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>

            </ul>

        </nav>
        <!-- End of Topbar -->
        <div class="pt-3">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

        <div class="container-fluid mt-4">
            <h1>Welcome {{current_user.name}}!</h1>
            <p class="small fw-bold mt-2 pt-1 mb-0">New Employee? <a href="{{url_for('auth.registerUser')}}"
                    class="link-danger">Click To Register</a></p>

            <!-- Matumizi -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 text-center">
                    <h3 class="m-0 font-weight-bold ">Admin Dashboard</h3>
                </div>
                <div class="card-body">
                    <section>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Role</th>
                                    <th>Status</th>

                                </tr>
                            </thead>
                            <tbody>
                                <!-- User rows will be populated here -->
                                {% if users %}
                                {% for user in users %}
                                {% if user.id >= 2 %}
                                <tr>
                                    <td>{{loop.index -1 }}</td>
                                    <td>{{user.name}}</td>
                                    <td>{{user.email}}</td>
                                    <td>{{user.phone_no}}</td>
                                    <td>{{user.position_as}}</td>

                                    <td>
                                        <a href="/delete_account/{{ user.id }}" class="btn btn-outline-dark">Delete</a>
                                        {% if user.is_active %}
                                        <a href="/deactivate_account/{{ user.id }}"
                                            class="btn btn-outline-dark">Pending</a>
                                        {% else %}
                                        <a href="/activate_account/{{ user.id }}"
                                            class="btn btn-outline-dark">Resume</a>
                                        {% endif %}
                                    </td>
                                </tr>

                                {% endif %}
                                {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </section>


                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>

</html>